server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: stock-price
          uri: lb://stock-price-service
          predicates:
            - Path=/stock-price/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
